local opt = { silent = true, nowait = true }
vim.keymap.set("v", "<C-c>", [["+y]], opt)
vim.keymap.set("i", "<C-v>", "<C-R><C-O>+", opt)
vim.keymap.set("i", "<C-F>", "<C-X><C-F>", opt)
vim.keymap.set("i", "<C-L>", "<C-X><C-L>", opt)
vim.keymap.set("c", "<C-A>", "<HOME>", {noremap = true})
vim.keymap.set({"c", "i"}, "<C-F>", "<Right>", {noremap = true})
vim.keymap.set({"c", "i"}, "<C-B>", "<Left>", {noremap = true})
vim.keymap.set({"c", "i"}, "<C-B>", "<Left>", {noremap = true})
vim.keymap.set("c", "<A-b>", "<C-Left>", {noremap = true})
vim.keymap.set("c", "<A-f>", "<C-Right>", {noremap = true})
vim.keymap.set("c", "<C-K>", function ()
	vim.fn.setcmdline(vim.fn.strpart(vim.fn.getcmdline(), 0, vim.fn.getcmdpos() - 1 ))
end, {noremap = true})
vim.keymap.set("t", "<Esc>", [[<C-\><C-n>]], {noremap = true})
vim.keymap.set("n", "\\", "@@", {noremap = true, silent = true, desc = "List dot repeat previous macro."})
vim.keymap.set('n', 'gp', "<CMD>put \"<CR>", { desc = "Paste below."})
vim.keymap.set('n', 'gP', "<CMD>-1put \"<CR>", { desc = "Paste above."})
vim.keymap.set('n', '[P', "i ", { desc = "Paste space to left."})
vim.keymap.set('n', ']P', "a ", { desc = "Paste space to right."})
